name: trading_app
description: "A trading app in Flutter."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  toastification: ^3.0.3
  shared_preferences: ^2.5.3
  provider: ^6.1.5
  json_annotation: ^4.9.0
  searchfield:
    git:
      url: https://github.com/maheshj01/searchfield.git
      ref: 2045cd8
  intl: ^0.20.2
  excel: ^4.0.6
  file_picker: ^10.3.8
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.10.1
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  